"""Updating_user_model

Revision ID: 279e01148402
Revises: 8424471d22f2
Create Date: 2026-06-22 15:53:26.602576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '279e01148402'
down_revision: Union[str, Sequence[str], None] = '8424471d22f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_index(op.f('ix_users_firstName'), table_name='users')
    op.drop_index(op.f('ix_users_isComplete'), table_name='users')
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_is_complete'), 'users', ['is_complete'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'isComplete')
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'firstName')
    op.drop_column('users', 'createdAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('isComplete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_complete'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    op.create_index(op.f('ix_users_isComplete'), 'users', ['isComplete'], unique=False)
    op.create_index(op.f('ix_users_firstName'), 'users', ['firstName'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_complete')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
